version: "3"
services:
   mysql:
      image: mysql:8.0
      container_name: mysql8
      restart: always
      ports:
         - "${DB_PORT}:${DB_PORT}"
      environment:
         MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
         MYSQL_PASSWORD: "${DB_PASSWORD}"
         MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      volumes:
         - "/Users/carvalho/.db/.data/mysql8:/var/lib/mysql"
      networks:
         - local
networks:
   local:
      driver: bridge
